### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by soyraro** [BRACKETS-by-TRIAD/simpleweb#1]
Hi... I get this error after artisan install

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in
   your SQL syntax; check the manual that corresponds to your MySQL server ver
  sion for the right syntax to use near 'WHERE deleted_at IS NULL' at line 1 (
  SQL: CREATE UNIQUE INDEX users_email_null_deleted_at ON users (email) WHERE
  deleted_at IS NULL;)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in
   your SQL syntax; check the manual that corresponds to your MySQL server ver
  sion for the right syntax to use near 'WHERE deleted_at IS NULL' at line 1

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in
   your SQL syntax; check the manual that corresponds to your MySQL server ver
  sion for the right syntax to use near 'WHERE deleted_at IS NULL' at line 1

**Comment by palypster** [comment]
@soyraro I guess we have missed, that MySQL does not support partial indexes (we primarily develop for PostgreSQL). We will sort it out in final release (coming up very soon).

**Comment by palypster** [comment]
We have a fix in dev version of a dependent package.

If you don't want to wait more for a final release and if you have used https://github.com/BRACKETS-by-TRIAD/simpleweb-installer , then I recommend you to update it:
```
composer global update brackets/simpleweb-installer
```

Once updated, you can use `--dev` option to grab the latest, non-stable version of SimpleWEB and its dependencies:
```
simpleweb new --dev my project
```

**Comment by soyraro** [comment]
Thanks for your help... cheers!
